PREFIX DTDFvocab:   <https://bentleyjoakes.github.io/DTDF/vocab/DTDFVocab#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?model
WHERE {
	?model a DTDFvocab:Model .
}
GROUP BY ?model