PREFIX DTDFvocab:   <https://bentleyjoakes.github.io/DTDF/vocab/DTDFVocab#>
PREFIX rdfs:        <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?service
WHERE {
	?service a DTDFvocab:Service .
}
GROUP BY ?service